### PR TITLE
feat: added custom logger instance

### PR DESCRIPTION
**Pull request by kaname-png**

### CODE REVIEW

**Comment by ramiel** [comment]
Hey, hello. Thanks for the pull request, but your changeset is including style changes (spaces, formatting and so on). It's not your fault, I never enforced it. I'll make sure I'll include some style constrainst (through eslint+prettier). Either you wait or you just push changes about the logger and nothing else

**Comment by ramiel** [comment]
You can rebase changes on latest `main` that now contains a linter

**Comment by kaname-png** [comment]
@ramiel done.

**Comment by ramiel** [comment]
In order for the test to pass you have to remove all of yours style settings. This PR is about the logger, don't change any not related line. Thanks

**Comment by kaname-png** [comment]
@ramiel sorry, done. :D

**Comment by ramiel** [comment]
Thank you!

**Comment by ramiel** [comment]
Available in version 3.2.0

**Pull request merged**
